# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  base = "client/"

  publish = "client/build/"
  command = "yarn build"

[context.production]
  REACT_APP_BACKEND_URL="http://polygive.herokuapp.com/"